from __future__ import annotations

from laitoxx.app.catalog import ToolSpec

TOOL_REGISTRY: dict[str, ToolSpec] = {
    "IOC Extractor": ToolSpec(
        handler="laitoxx.features.utilities.ioc_extractor:ioc_extractor_tool",
        input_type="text",
        prompt="Paste text, logs, headers, or an email:",
        desc="Extract IPs, domains, URLs, emails, phones, hashes, JWTs, and usernames.",
        threaded=False,
    ),
    "Check IP": ToolSpec(
        handler="laitoxx.features.network.ip_info:get_ip",
        input_type="network_info_ip",
        prompt="Enter IP address:",
        desc="Get geolocation data for an IP address.",
        threaded=True,
    ),
    "Domain Intelligence": ToolSpec(
        handler="laitoxx.features.web_audit.domain_intelligence:domain_intelligence",
        input_type="network_info_website",
        prompt="Enter domain or URL:",
        desc="DNS, RDAP registration, HTTP, TLS and certificate intelligence for a domain.",
        threaded=True,
    ),
    "Email OSINT": ToolSpec(
        handler="laitoxx.features.osint.email_osint:email_osint",
        input_type="text",
        prompt="Enter email address (or a Gmail prefix):",
        desc="Validate an address, inspect its mail domain and run public email enrichment.",
        threaded=True,
    ),
    "Database search": ToolSpec(
        handler="laitoxx.features.osint.db_searcher:search_database",
        input_type="text",
        prompt="Enter search query (e.g., email, name):",
        desc="Search for leaks in local databases.",
        threaded=True,
    ),
    "Check MAC-address": ToolSpec(
        handler="laitoxx.features.network.mac_lookup:search_mac_address",
        input_type="network_info_mac",
        prompt="Enter MAC address:",
        desc="Lookup the vendor and location of a MAC address (via Apple WPS).",
        threaded=True,
    ),
    "Google Osint": ToolSpec(
        handler="laitoxx.features.osint.google_osint:google_osint",
        input_type="google_osint",
        prompt=None,
        desc="Build advanced Google dorks with multiple operators.",
        threaded=False,
    ),
    "Search Nick": ToolSpec(
        handler="laitoxx.features.osint.username_osint:username_osint_tool",
        input_type="username_osint_dialog",
        prompt=None,
        desc="Advanced Username OSINT: 500+ sites, nickname generation, graph integration.",
        threaded=False,
    ),
    "Web Crawler": ToolSpec(
        handler="laitoxx.features.web_audit.crawler:web_crawler",
        input_type="web_crawler",
        prompt=None,
        desc="Bounded website crawl with scope controls, forms, endpoints, reports and graph export.",
        threaded=False,
    ),
    "Masscan Scanner": ToolSpec(
        handler="laitoxx.features.network.masscan_scanner:masscan_scanner_tool",
        input_type="masscan",
        prompt=None,
        desc="masscan_tool_desc",
        threaded=False,
    ),
    "HTTP Inspector": ToolSpec(
        handler="laitoxx.features.web_audit.http_inspector:http_inspector",
        input_type="text",
        prompt="Enter URL to inspect:",
        desc="Status, all headers, redirect chain, TLS cert, cookies.",
        threaded=True,
    ),
    "Tech Detector": ToolSpec(
        handler="laitoxx.features.web_audit.tech_detector:tech_detector",
        input_type="text",
        prompt="Enter URL to fingerprint:",
        desc="Fingerprint server, CDN, CMS, JS frameworks, WAF, security headers.",
        threaded=True,
    ),
    "CMS Audit": ToolSpec(
        handler="laitoxx.features.web_audit.cms_audit:cms_audit",
        input_type="text",
        prompt="Enter target URL for CMS audit:",
        desc="Passive CMS audit: version, robots.txt, security.txt, sitemap, exposed files.",
        threaded=True,
    ),
    "Text Hasher": ToolSpec(
        handler="laitoxx.features.crypto.hash_tools.text_hasher:text_hasher_tool",
        input_type="hash",
        prompt=None,
        desc="Hash text using various algorithms (MD5, SHA256, etc.).",
        threaded=True,
    ),
    "Hash Identifier": ToolSpec(
        handler="laitoxx.features.crypto.hash_tools.hash_identifier:hash_identifier_tool",
        input_type="hash",
        prompt=None,
        desc="Identify the type of a given hash.",
        threaded=True,
    ),
    "Rainbow Table Gen": ToolSpec(
        handler="laitoxx.features.crypto.hash_tools.rainbow_table_generator:rainbow_table_tool",
        input_type="hash",
        prompt=None,
        desc="Generate a rainbow table for a given charset and hash.",
        threaded=True,
    ),
    "JWT Analyzer": ToolSpec(
        handler="laitoxx.features.crypto.jwt_analyzer:jwt_analyzer_tool",
        input_type="jwt",
        prompt=None,
        desc="Decode & inspect JWT tokens, or brute-force HMAC secret (HS256/384/512).",
        threaded=True,
    ),
    "Web Security Tools": ToolSpec(
        handler="laitoxx.features.web_audit.web_security_tools:web_security_tools",
        input_type="web_security",
        prompt=None,
        desc="SSL/TLS, CORS, Open Redirect, and Security Headers checks.",
        threaded=True,
    ),
    "Text Cipher": ToolSpec(
        handler="laitoxx.features.utilities.text_cipher:text_cipher_tool",
        input_type="text_cipher",
        prompt=None,
        desc="Encode, decode and inspect text across 86 local transformations.",
        threaded=False,
    ),
    "Password Generator": ToolSpec(
        handler="laitoxx.features.crypto.password_generator:password_generator_tool",
        input_type="password_gen",
        prompt=None,
        desc="Generate secure passwords with custom charset, include/exclude rules.",
        threaded=False,
    ),
    "Regex Tester": ToolSpec(
        handler="laitoxx.features.utilities.regex_tester:regex_tester_tool",
        input_type="regex",
        prompt=None,
        desc="Test a regex pattern against text - shows all matches, groups, line:col.",
        threaded=False,
    ),
    "CIDR Calculator": ToolSpec(
        handler="laitoxx.features.network.cidr_calculator:cidr_calculator_tool",
        input_type="cidr",
        prompt=None,
        desc="IPv4/IPv6 network info, IP membership check, subnet splitting.",
        threaded=False,
    ),
    "Image Search": ToolSpec(
        handler="laitoxx.features.osint.image_search:image_search_tool",
        input_type="image_search",
        prompt=None,
        desc="Обратный поиск изображений + криминалистический анализ: ELA, EXIF, хэши, редактор.",
        threaded=False,
    ),
    "Metadata Viewer": ToolSpec(
        handler="laitoxx.features.utilities.metadata_viewer:metadata_viewer_tool",
        input_type="metadata_viewer",
        prompt=None,
        desc="Advanced metadata analysis, forensics, privacy scoring and sanitization.",
        threaded=False,
    ),
    "Steganography": ToolSpec(
        handler="laitoxx.features.utilities.steganography.wrapper:steganography_tool",
        input_type="steganography",
        prompt=None,
        desc="Hide or extract secret data within image files.",
        threaded=True,
    ),
    "Advanced Web Scanner": ToolSpec(
        handler="laitoxx.features.osint.advanced_web_scanner:advanced_web_scanner_tool",
        input_type="advanced_web_scanner",
        prompt=None,
        desc="Correlate DNS, registration, exposure, threat intelligence and vulnerability data in one graph and timeline.",
        threaded=False,
    ),
    "TONgue": ToolSpec(
        handler="laitoxx.features.osint.tongue.service:tongue_tool",
        input_type="tongue",
        prompt=None,
        desc="Start from Telegram or TON and connect public profiles, Gifts, NFTs and wallets in one evidence graph.",
        threaded=False,
    ),
    "CogniPass": ToolSpec(
        handler="laitoxx.features.utilities.cognipass:cognipass_tool",
        input_type="cognipass",
        prompt=None,
        desc="cognipass_tool_desc",
        threaded=False,
    ),
}

CATEGORIES: dict[str, list[str]] = {
    # UI order is intentional: append newly exposed tools to the end of a category.
    "information_gathering": [
        "Check IP",
        "Domain Intelligence",
        "Email OSINT",
        "Database search",
        "Check MAC-address",
        "Google Osint",
        "Search Nick",
        "Web Crawler",
        "Image Search",
        "IOC Extractor",
        "TONgue",
    ],
    "web_security": [
        "Masscan Scanner",
        "HTTP Inspector",
        "Tech Detector",
        "CMS Audit",
        "JWT Analyzer",
        "Web Security Tools",
        "Advanced Web Scanner",
    ],
    "utils": [
        "Text Hasher",
        "Hash Identifier",
        "Rainbow Table Gen",
        "Text Cipher",
        "Password Generator",
        "Regex Tester",
        "CIDR Calculator",
        "Metadata Viewer",
        "Steganography",
        "CogniPass",
    ],
}
