"""Focused behavior slice for TongueWindow."""
# ruff: noqa: F405

from .tongue_window_context import *  # noqa: F403


class TongueWindowMixin1:
    def _build_ui(self):
        root = QVBoxLayout(self)
        root.setContentsMargins(12, 10, 12, 10)
        root.setSpacing(8)

        hero = QFrame()
        hero.setObjectName("PageHeader")
        hero.setMaximumHeight(82)
        hero_layout = QHBoxLayout(hero)
        hero_layout.setContentsMargins(16, 10, 16, 10)
        self.brand_mark = _BrandIcon("ton", 48)
        self.brand_mark.setToolTip("TON Blockchain")
        hero_layout.addWidget(self.brand_mark)
        title_box = QVBoxLayout()
        title_box.setSpacing(1)
        title = QLabel(_t("TONgue"))
        title.setObjectName("PageTitle")
        subtitle = QLabel(_t("tongue_subtitle", "Start with Telegram, then connect public Gifts, NFTs and TON wallets"))
        subtitle.setObjectName("PageSubtitle")
        title_box.addWidget(title)
        title_box.addWidget(subtitle)
        hero_layout.addLayout(title_box)
        hero_layout.addStretch()
        root.addWidget(hero)

        query_panel = QFrame()
        query_panel.setObjectName("PanelSurface")
        query = QHBoxLayout(query_panel)
        query.setContentsMargins(12, 9, 12, 9)
        query.setSpacing(8)
        self.target_input = QLineEdit()
        self.target_input.setPlaceholderText(
            _t("tongue_target_placeholder", "@username, t.me link, Telegram ID, Gift, NFT or TON wallet")
        )
        self.target_input.returnPressed.connect(self._start)
        query.addWidget(self.target_input, 1)
        self.kind_combo = QComboBox()
        self.kind_combo.setMinimumWidth(170)
        for text, value in (
            (_t("tongue_type_auto", "Detect automatically"), "auto"),
            (_t("tongue_type_telegram", "Telegram profile / channel"), "telegram"),
            (_t("tongue_type_wallet", "Wallet"), "wallet"),
            (_t("tongue_type_nft", "NFT item"), "nft"),
            (_t("tongue_type_gift", "Telegram Gift"), "gift"),
        ):
            self.kind_combo.addItem(text, value)
        query.addWidget(self.kind_combo)
        self.start_button = QPushButton(_t("tongue_start", "Search & investigate"))
        self.start_button.setProperty("variant", "primary")
        self.start_button.clicked.connect(self._start)
        query.addWidget(self.start_button)
        self.cancel_button = QPushButton(_t("tongue_cancel", "Stop"))
        self.cancel_button.setEnabled(False)
        self.cancel_button.clicked.connect(self._cancel)
        query.addWidget(self.cancel_button)
        root.addWidget(query_panel)

        workspace = QSplitter(Qt.Orientation.Horizontal)
        workspace.setChildrenCollapsible(False)
        root.addWidget(workspace, 1)

        sidebar_scroll = QScrollArea()
        sidebar_scroll.setObjectName("TongueSidebarScroll")
        sidebar_scroll.viewport().setObjectName("TongueSidebarViewport")
        sidebar_scroll.setWidgetResizable(True)
        sidebar_scroll.setFrameShape(QFrame.Shape.NoFrame)
        sidebar_scroll.setMinimumWidth(285)
        sidebar_scroll.setMaximumWidth(370)
        sidebar = QWidget()
        sidebar.setObjectName("TongueSidebar")
        options = QVBoxLayout(sidebar)
        options.setContentsMargins(12, 12, 12, 12)
        options.setSpacing(8)

        section = QLabel(_t("tongue_search_scope", "SEARCH DEPTH"))
        section.setObjectName("SectionLabel")
        options.addWidget(section)
        self.profile_combo = QComboBox()
        self.profile_combo.addItem(_t("tongue_profile_quick", "Quick"), "quick")
        self.profile_combo.addItem(_t("tongue_profile_balanced", "Balanced"), "balanced")
        self.profile_combo.addItem(_t("tongue_profile_deep", "Deep"), "deep")
        self.profile_combo.setCurrentIndex(1)
        self.profile_combo.currentIndexChanged.connect(self._apply_profile)
        options.addWidget(self.profile_combo)
        self.recursive = QCheckBox(_t("tongue_recursive", "Recursive evidence graph"))
        self.recursive.setChecked(True)
        options.addWidget(self.recursive)
        depth_row = QHBoxLayout()
        depth_row.addWidget(QLabel(_t("tongue_depth", "Depth")))
        depth_row.addStretch()
        self.depth = QSpinBox()
        self.depth.setRange(0, 6)
        self.depth.setValue(3)
        self.depth.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.depth.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.depth.setFixedWidth(74)
        depth_row.addWidget(self.depth)
        step_buttons = QVBoxLayout()
        step_buttons.setSpacing(2)
        step_buttons.setContentsMargins(0, 0, 0, 0)
        self.depth_up = QToolButton()
        self.depth_down = QToolButton()
        for button in (self.depth_up, self.depth_down):
            button.setProperty("spinControl", True)
            button.setAutoRepeat(True)
            button.setFixedSize(28, 17)
        self.depth_up.setToolTip(_t("tongue_depth_increase", "Increase depth"))
        self.depth_down.setToolTip(_t("tongue_depth_decrease", "Decrease depth"))
        self.depth_up.clicked.connect(self.depth.stepUp)
        self.depth_down.clicked.connect(self.depth.stepDown)
        step_buttons.addWidget(self.depth_up)
        step_buttons.addWidget(self.depth_down)
        depth_row.addLayout(step_buttons)
        options.addLayout(depth_row)
        self.public_profiles = QCheckBox(_t("tongue_public_profiles", "Public Telegram profiles"))
        self.public_profiles.setChecked(True)
        options.addWidget(self.public_profiles)
        self.blockchain_gifts = QCheckBox(_t("tongue_blockchain_gifts", "Resolve Gift contracts in TON"))
        self.blockchain_gifts.setChecked(True)
        options.addWidget(self.blockchain_gifts)
        self.trace_sales = QCheckBox(_t("tongue_trace_sales", "Classify sales from traces"))
        options.addWidget(self.trace_sales)
        self.preserve_raw = QCheckBox(_t("tongue_preserve_raw", "Preserve raw evidence"))
        options.addWidget(self.preserve_raw)
        self.price_estimates = QCheckBox(_t("tongue_price_estimates", "Historical TON/USD estimates"))
        self.price_estimates.setChecked(True)
        self.price_estimates.setToolTip(
            _t(
                "tongue_price_estimates_tip",
                "Uses a public CoinGecko historical range; values are approximate.",
            )
        )
        options.addWidget(self.price_estimates)

        api_title = QLabel(_t("tongue_sources", "PUBLIC SOURCES"))
        api_title.setObjectName("SectionLabel")
        options.addWidget(api_title)
        options.addWidget(QLabel(_t("tongue_api_key", "TON Center key")))
        self.api_key = QLineEdit()
        self.api_key.setEchoMode(QLineEdit.EchoMode.Password)
        self.api_key.setPlaceholderText(_t("tongue_api_optional_short", "Optional"))
        self.api_key.setText(str(settings.tongue.get("api_key", "")))
        options.addWidget(self.api_key)
        options.addWidget(QLabel(_t("tongue_tonapi_key", "TonAPI key")))
        self.tonapi_key = QLineEdit()
        self.tonapi_key.setEchoMode(QLineEdit.EchoMode.Password)
        self.tonapi_key.setPlaceholderText(_t("tongue_tonapi_optional", "Optional · raises public index limits"))
        self.tonapi_key.setText(str(settings.tongue.get("tonapi_key", "")))
        options.addWidget(self.tonapi_key)
        options.addStretch()

        status_card = QFrame()
        status_card.setObjectName("PanelSurface")
        status_layout = QVBoxLayout(status_card)
        status_layout.setContentsMargins(10, 8, 10, 8)
        self.status = QLabel(_t("tongue_ready_short", "Enter a Telegram username or TON entity to begin"))
        self.status.setObjectName("Muted")
        self.status.setWordWrap(True)
        status_layout.addWidget(self.status)
        self.stats = QLabel("-")
        self.stats.setObjectName("Muted")
        status_layout.addWidget(self.stats)
        self.progress = QProgressBar()
        self.progress.setTextVisible(False)
        self.progress.setRange(0, 1)
        self.progress.setValue(0)
        self.progress.setFixedHeight(4)
        status_layout.addWidget(self.progress)
        options.addWidget(status_card)

        action_grid = QVBoxLayout()
        self.export_button = QPushButton(_t("tongue_export_json", "Export JSON"))
        self.export_button.setEnabled(False)
        self.export_button.clicked.connect(self._export_json)
        action_grid.addWidget(self.export_button)
        self.report_button = QPushButton(_t("tongue_open_report", "HTML report"))
        self.report_button.setEnabled(False)
        self.report_button.clicked.connect(self._open_report)
        action_grid.addWidget(self.report_button)
        self.folder_button = QPushButton(_t("tongue_open_folder", "Evidence folder"))
        self.folder_button.clicked.connect(self._open_folder)
        action_grid.addWidget(self.folder_button)
        options.addLayout(action_grid)
        sidebar_scroll.setWidget(sidebar)
        workspace.addWidget(sidebar_scroll)

        self.tabs = QTabWidget()
        workspace.addWidget(self.tabs)
        workspace.setStretchFactor(0, 0)
        workspace.setStretchFactor(1, 1)
        workspace.setSizes([320, 1100])
        self._build_summary_tab()
        self._build_entities_tab()
        self._build_timeline_tab()
        self._build_graph_tab()
        self._build_json_tab()
