"""Static negative profile markers."""

PRIMARY_NEGATIVE_PHRASES = [
    "user not found",
    "page not found",
    "profile not found",
    "account not found",
    "no results found",
    "0 results found",
    "no such user",
    "does not exist",
    "doesn't exist",
    "not exist",
    "could not be found",
    "has been removed",
    "has been deleted",
    "has been suspended",
    "has been banned",
    "account suspended",
    "account disabled",
    "account deactivated",
    "nothing here",
    "content unavailable",
    "we couldn't find",
    "no matching user",
    "member not found",
    "invalid username",
    "username not found",
    "no profile found",
    "user is not registered",
    "error 404",
    "this user hasn't",
    "this user has not",
    "no account",
    "profile is not available",
    "user unavailable",
    "account unavailable",
    "profile unavailable",
    "user missing",
    "account missing",
    "profile missing",
    "no such account",
    "no such profile",
    "user does not exist",
    "account does not exist",
    "profile does not exist",
    "user cannot be found",
    "account cannot be found",
    "user was deleted",
    "account was deleted",
    "user removed",
    "account removed",
    "user suspended",
    "user banned",
    "account banned",
    "user deactivated",
    "account deactivated",
    "user invalid",
    "account invalid",
    "profile invalid",
    "user lookup failed",
    "profile lookup failed",
    "page unavailable",
    "page missing",
    "page removed",
    "resource not found",
    "requested user not found",
    "requested page not found",
    "requested profile not found",
    "The specified member cannot be found",
    "Page not found",
    "404 Not Found",
    "Sorry, we couldn't find what you were looking for.",
    "this profile does not exist",
    "the account you're looking for is not available",
    "no such profile exists",
    "username does not exist",
    "could not find the user",
    "the page has been removed or does not exist",
    "account has been deleted by the owner",
    "this user is not on the platform",
    "no matching results for this user",
    "profile has been suspended",
    "the requested account cannot be found",
    "404 - profile not found",
    "we couldn't locate this profile",
    "this account has been terminated",
    "no user found matching your search",
    "the member has been removed",
    "page not found for this username",
    "account is no longer active",
    "this profile is unavailable",
    "couldn't find any account with that name",
    "the user has been banned from the platform",
    "no records found for this profile",
    "this page does not exist anymore",
    "invalid or non-existent user",
    "account lookup failed - user not found",
    "the profile you requested has been deleted",
    "no active account associated with this username",
    "we are sorry, but this user does not exist",
    "the specified user cannot be found",
    "profile not found in our database",
    "this account has been closed permanently",
    "user data could not be retrieved",
    "no such user on our servers",
    "the page is missing or has been taken down",
    "account has been deactivated and is not viewable",
    "could not retrieve the requested profile",
    "this username is not registered or has been removed",
    "no results found for the user query",
    "the member account is not available",
    "page unavailable - user not found",
    "this content is no longer available due to account deletion",
    "the user profile has been archived",
    "no account found with the provided details",
    "oops! the profile does not exist",
    "we couldn't find what you were looking for - user",
    "the account has been purged from the system",
    "profile cannot be accessed at this time",
    "no user with that username exists",
    "the requested page is not found or deleted",
    "account has been removed due to violation",
    "this profile was not found",
    "search returned no matching users",
    "the user you are trying to view does not exist",
    "account not found - please check the username",
    "this page has been deleted by the user",
    "no profile associated with this account",
    "the member cannot be found on the platform",
    "404 error: user profile not found",
    "we are unable to display this profile",
    "the account is invalid or has been suspended",
    "no data found for this user",
    "user not found in the system",
    "the profile has been taken down",
    "This account may have been banned or the username is incorrect.",
    "No users matched your search",
    "пользователь не найден",
    "страница не найдена",
    "профиль не найден",
    "аккаунт не найден",
    "ничего не найдено",
    "результатов не найдено",
    "нет такого пользователя",
    "не существует",
    "удалена",
    "заблокирована",
    "заблокирован",
    "0 результатов",
    "нет пользователя",
    "профиль удален",
    "аккаунт удален",
    "пользователь удален",
    "страница удалена",
    "аккаунт заблокирован",
    "пользователь заблокирован",
    "аккаунт деактивирован",
    "пользователь деактивирован",
    "профиль недоступен",
    "страница недоступна",
    "аккаунт недоступен",
    "пользователь недоступен",
    "ничего не найдено по запросу",
    "результаты отсутствуют",
    "пользователь отсутствует",
    "аккаунт отсутствует",
    "не удалось найти пользователя",
    "не удалось найти профиль",
    "ошибка 404",
    "ресурс не найден",
    "данные не найдены",
    "профиль не существует",
    "Упс",
    "этот профиль не существует",
    "аккаунт, который вы ищете, недоступен",
    "такого профиля не существует",
    "имя пользователя не существует",
    "страница удалена или не существует",
    "аккаунт удалён владельцем",
    "этот пользователь не на платформе",
    "нет совпадающих результатов для этого пользователя",
    "профиль заблокирован",
    "запрашиваемый аккаунт не может быть найден",
    "404 - профиль не найден",
    "мы не смогли найти этот профиль",
    "этот аккаунт был прекращён",
    "пользователь не найден по вашему поиску",
    "участник был удалён",
    "страница не найдена для этого имени пользователя",
    "аккаунт больше не активен",
    "этот профиль недоступен",
    "не удалось найти аккаунт с таким именем",
    "пользователь был заблокирован на платформе",
    "нет записей для этого профиля",
    "эта страница больше не существует",
    "недействительный или несуществующий пользователь",
    "поиск аккаунта не удался - пользователь не найден",
    "профиль, который вы запросили, был удалён",
    "нет активного аккаунта, связанного с этим именем пользователя",
    "мы сожалеем, но этот пользователь не существует",
    "указанный пользователь не может быть найден",
    "профиль не найден в нашей базе данных",
    "этот аккаунт был закрыт навсегда",
    "данные пользователя не удалось получить",
    "такого пользователя нет на наших серверах",
    "страница отсутствует или была удалена",
    "аккаунт деактивирован и недоступен для просмотра",
    "не удалось получить запрошенный профиль",
    "это имя пользователя не зарегистрировано или было удалено",
    "результатов не найдено по запросу пользователя",
    "аккаунт участника недоступен",
    "страница недоступна - пользователь не найден",
    "этот контент больше недоступен из-за удаления аккаунта",
    "профиль пользователя был архивирован",
    "аккаунт не найден по предоставленным данным",
    "упс! профиль не существует",
    "мы не смогли найти то, что вы искали - пользователь",
    "аккаунт был очищен из системы",
    "профиль невозможно открыть в данный момент",
    "пользователя с таким именем не существует",
    "запрашиваемая страница не найдена или удалена",
    "аккаунт был удалён из-за нарушения",
]
