"""Static negative profile markers."""

EXTENDED_NEGATIVE_PHRASES = [
    "этот профиль не найден",
    "поиск не вернул совпадающих пользователей",
    "пользователь, которого вы пытаетесь просмотреть, не существует",
    "аккаунт не найден - проверьте имя пользователя",
    "эта страница была удалена пользователем",
    "профиль не связан с этим аккаунтом",
    "участник не может быть найден на платформе",
    "ошибка 404: профиль пользователя не найден",
    "мы не можем отобразить этот профиль",
    "аккаунт недействителен или заблокирован",
    "данные для этого пользователя не найдены",
    "пользователь не найден в системе",
    "профиль был удалён",
    "Кажется, этой страницы не существует",
    "benutzer nicht gefunden",
    "seite nicht gefunden",
    "profil nicht gefunden",
    "kein benutzer",
    "keine ergebnisse",
    "existiert nicht",
    "nicht gefunden",
    "konto nicht gefunden",
    "benutzer existiert nicht",
    "dieses profil existiert nicht",
    "das konto, das du suchst, ist nicht verfügbar",
    "ein solches profil existiert nicht",
    "benutzername existiert nicht",
    "die seite wurde entfernt oder existiert nicht",
    "konto wurde vom besitzer gelöscht",
    "dieser benutzer ist nicht auf der plattform",
    "keine passenden ergebnisse für diesen benutzer",
    "profil wurde gesperrt",
    "das angeforderte konto konnte nicht gefunden werden",
    "404 - profil nicht gefunden",
    "wir konnten dieses profil nicht finden",
    "dieses konto wurde beendet",
    "kein benutzer gefunden, der deiner suche entspricht",
    "das mitglied wurde entfernt",
    "seite nicht gefunden für diesen benutzernamen",
    "konto ist nicht mehr aktiv",
    "dieses profil ist nicht verfügbar",
    "konnte kein konto mit diesem namen finden",
    "der benutzer wurde von der plattform gesperrt",
    "keine einträge für dieses profil gefunden",
    "diese seite existiert nicht mehr",
    "ungültiger oder nicht existierender benutzer",
    "konto-suche fehlgeschlagen - benutzer nicht gefunden",
    "das angeforderte profil wurde gelöscht",
    "kein aktives konto mit diesem benutzernamen verknüpft",
    "wir bedauern, aber dieser benutzer existiert nicht",
    "der angegebene benutzer konnte nicht gefunden werden",
    "profil nicht in unserer datenbank gefunden",
    "dieses konto wurde dauerhaft geschlossen",
    "benutzerdaten konnten nicht abgerufen werden",
    "kein solcher benutzer auf unseren servern",
    "die seite fehlt oder wurde entfernt",
    "konto wurde deaktiviert und ist nicht einsehbar",
    "das angeforderte profil konnte nicht abgerufen werden",
    "dieser benutzername ist nicht registriert oder wurde entfernt",
    "keine ergebnisse für die benutzersuche gefunden",
    "mitgliedskonto ist nicht verfügbar",
    "seite nicht verfügbar - benutzer nicht gefunden",
    "dieser inhalt ist nicht mehr verfügbar wegen konto-löschung",
    "das benutzerprofil wurde archiviert",
    "konto nicht gefunden mit den angegebenen details",
    "ups! das profil existiert nicht",
    "wir konnten nicht finden, wonach du gesucht hast - benutzer",
    "das konto wurde aus dem system entfernt",
    "profil kann derzeit nicht aufgerufen werden",
    "kein benutzer mit diesem benutzernamen existiert",
    "die angeforderte seite wurde nicht gefunden oder gelöscht",
    "konto wurde wegen verstoßes entfernt",
    "dieses profil wurde nicht gefunden",
    "suche ergab keine passenden benutzer",
    "der benutzer, den du ansehen möchtest, existiert nicht",
    "konto nicht gefunden - bitte benutzernamen überprüfen",
    "diese seite wurde vom benutzer gelöscht",
    "kein profil mit diesem konto verknüpft",
    "das mitglied kann auf der plattform nicht gefunden werden",
    "fehler 404: benutzerprofil nicht gefunden",
    "wir können dieses profil nicht anzeigen",
    "das konto ist ungültig oder gesperrt",
    "keine daten für diesen benutzer gefunden",
    "benutzer nicht im system gefunden",
    "das profil wurde entfernt",
    "utilisateur introuvable",
    "page introuvable",
    "profil introuvable",
    "utilisateur non trouvé",
    "aucun résultat",
    "n'existe pas",
    "compte introuvable",
    "ce profil n'existe pas",
    "le compte que vous recherchez n'est pas disponible",
    "un tel profil n'existe pas",
    "nom d'utilisateur inexistant",
    "impossible de trouver l'utilisateur",
    "la page a été supprimée ou n'existe pas",
    "compte supprimé par le propriétaire",
    "cet utilisateur n'est pas sur la plateforme",
    "aucun résultat correspondant pour cet utilisateur",
    "profil suspendu",
    "le compte demandé est introuvable",
    "404 - profil introuvable",
    "nous n'avons pas pu localiser ce profil",
    "ce compte a été terminé",
    "aucun utilisateur trouvé correspondant à votre recherche",
    "le membre a été supprimé",
    "page introuvable pour ce nom d'utilisateur",
    "compte plus actif",
    "ce profil n'est pas disponible",
    "impossible de trouver un compte avec ce nom",
    "l'utilisateur a été banni de la plateforme",
    "aucun enregistrement trouvé pour ce profil",
    "cette page n'existe plus",
    "utilisateur invalide ou inexistant",
    "recherche de compte échouée - utilisateur introuvable",
    "le profil demandé a été supprimé",
    "aucun compte actif associé à ce nom d'utilisateur",
    "nous sommes désolés, mais cet utilisateur n'existe pas",
    "l'utilisateur spécifié est introuvable",
    "profil introuvable dans notre base de données",
    "ce compte a été fermé définitivement",
    "données utilisateur impossibles à récupérer",
    "aucun utilisateur de ce type sur nos serveurs",
    "la page est manquante ou a été retirée",
    "compte désactivé et non visible",
    "impossible de récupérer le profil demandé",
    "ce nom d'utilisateur n'est pas enregistré ou a été supprimé",
    "aucun résultat trouvé pour la requête utilisateur",
    "compte membre non disponible",
    "page indisponible - utilisateur introuvable",
    "ce contenu n'est plus disponible en raison de la suppression du compte",
    "le profil utilisateur a été archivé",
    "compte introuvable avec les détails fournis",
    "oups ! le profil n'existe pas",
    "nous n'avons pas pu trouver ce que vous cherchiez - utilisateur",
    "le compte a été purgé du système",
    "profil inaccessible pour le moment",
    "aucun utilisateur avec ce nom d'utilisateur n'existe",
    "la page demandée est introuvable ou supprimée",
    "compte supprimé pour violation",
    "ce profil n'a pas été trouvé",
    "la recherche n'a retourné aucun utilisateur correspondant",
    "l'utilisateur que vous essayez de voir n'existe pas",
    "compte introuvable - veuillez vérifier le nom d'utilisateur",
    "cette page a été supprimée par l'utilisateur",
    "aucun profil associé à ce compte",
    "le membre est introuvable sur la plateforme",
    "erreur 404 : profil utilisateur introuvable",
    "nous ne pouvons pas afficher ce profil",
    "le compte est invalide ou suspendu",
    "aucune donnée trouvée pour cet utilisateur",
    "utilisateur introuvable dans le système",
    "le profil a été retiré",
    "kullanıcı bulunamadı",
    "sayfa bulunamadı",
    "hesap bulunamadı",
    "profil bulunamadı",
    "bu profil mevcut değil",
    "aradığın hesap mevcut değil",
    "böyle bir profil mevcut değil",
    "sayfa silindi veya mevcut değil",
    "hesap sahibi tarafından silindi",
    "bu kullanıcı platformda değil",
    "bu kullanıcı için eşleşen sonuç yok",
    "profil askıya alındı",
    "istenen hesap bulunamıyor",
    "404 - profil bulunamadı",
    "bu profili bulamadık",
    "bu hesap sonlandırıldı",
    "aramanla eşleşen kullanıcı bulunamadı",
    "üye kaldırıldı",
    "bu kullanıcı adı için sayfa bulunamadı",
    "hesap artık aktif değil",
    "bu profil mevcut değil",
    "bu isimde hesap bulunamadı",
    "kullanıcı platformdan yasaklandı",
    "bu profil için kayıt bulunamadı",
    "bu sayfa artık mevcut değil",
    "geçersiz veya mevcut olmayan kullanıcı",
    "hesap araması başarısız - kullanıcı bulunamadı",
    "istediğin profil silindi",
    "bu kullanıcı adıyla aktif hesap yok",
    "üzgünüz ama bu kullanıcı mevcut değil",
    "belirtilen kullanıcı bulunamıyor",
    "profil veritabanımızda bulunamadı",
    "bu hesap kalıcı olarak kapatıldı",
    "kullanıcı verileri alınamadı",
    "sunucularımızda böyle bir kullanıcı yok",
    "sayfa eksik veya kaldırıldı",
    "hesap devre dışı bırakıldı ve görüntülenemiyor",
    "istenen profil alınamadı",
    "bu kullanıcı adı kayıtlı değil veya silinmiş",
    "kullanıcı sorgusu için sonuç bulunamadı",
    "üye hesabı mevcut değil",
    "sayfa kullanılamıyor - kullanıcı bulunamadı",
    "bu içerik hesap silinmesi nedeniyle artık mevcut değil",
    "kullanıcı profili arşivlendi",
    "sağlanan bilgilerle hesap bulunamadı",
    "eyvah! profil mevcut değil",
    "aradığını bulamadık - kullanıcı",
    "hesap sistemden temizlendi",
    "profil şu anda erişilemiyor",
    "bu kullanıcı adıyla kullanıcı mevcut değil",
    "istenen sayfa bulunamadı veya silindi",
    "hesap ihlal nedeniyle silindi",
    "bu profil bulunamadı",
    "arama eşleşen kullanıcı döndürmedi",
    "görüntülemeye çalıştığın kullanıcı mevcut değil",
    "hesap bulunamadı - kullanıcı adını kontrol et",
    "bu sayfa kullanıcı tarafından silindi",
    "bu hesapla ilişkili profil yok",
    "üye platformda bulunamıyor",
    "404 hatası: kullanıcı profili bulunamadı",
    "bu profili görüntüleyemiyoruz",
    "hesap geçersiz veya askıya alındı",
    "bu kullanıcı için veri bulunamadı",
    "kullanıcı sistemده bulunamadı",
    "profil kaldırıldı",
]
